id: P008044
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016276
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  volumes:
    92249a3f7a4843dbaa129de2e982e7d1:
      image_group_id: I00JW501165
      title: ''
      volume_number: 1
      total_pages: 620
ebook_metadata:
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  sku: P008044
  cover: cover.jpg
  layers:
  - pagination
