id: P008044
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1016276
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  volumes:
    d40add59ac1a4d8c844e540267569bf9:
      image_group_id: I00JW501165
      title: Volume 1 of gso rig man ngag gces btus rin chen gter mdzod a treatise
        on tibetan medical practice containing numerous instructions and formulae
      volume_number: 1
      total_pages: 620
      base_file: v001.txt
