id: opecha:P008044
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016276
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  volume:
    d40add59ac1a4d8c844e540267569bf9:
      image_group_id: I00JW501165
      title: Volume 1 of gso rig man ngag gces btus rin chen gter mdzod a treatise
        on tibetan medical practice containing numerous instructions and formulae
      volume_number: 1
      total_pages: 620
  author: ''
ebook_metadata:
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  sku: P008044
  cover: cover.jpg
  layers:
  - pagination
