id: I73638F78
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:09:44+00:00'
last_modified: '2022-06-08T18:01:56.785269+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016276
  title: གསོ་རིག་མན་ངག་གཅེས་བཏུས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A510:
      image_group_id: I00JW501165
      title: Volume 1 of gso rig man ngag gces btus rin chen gter mdzod a treatise
        on tibetan medical practice containing numerous instructions and formulae
      total_pages: 620
      order: 1
      base_file: A510.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
